name: markdown-link-check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Markdown links (offline/local)
        uses: lycheeverse/lychee-action@v2
        with:
          args: --offline --no-progress --verbose "./**/*.md"
          fail: true
